client:
  name: Connor Barwin
  risk_tolerance: moderate
  time_horizon_years: 10
  cash_buffer_pct: 10
  organization: Make the World Better Foundation
  background: Former NFL linebacker, Philadelphia Eagles front office
  initial_capital: 500000
  target_value: 1500000
  required_growth_rate: 11.61
  drawdown_start_year: 3
  annual_drawdown: 10000
  drawdown_growth_rate: 5
  foundation_mission: Community-driven capital projects in Philadelphia
  focus_areas:
  - Public space improvements
  - Park and community center revitalization
  - Safety and inclusivity initiatives
  - Long-term community stewardship
  track_record: $30+ million in community improvements since 2013
  final_project_target: Transformative community space modernization by 2036
universe:
  geography:
  - US
  - International (developed markets - max 20%)
  currency: USD
  benchmark: ^GSPC
  min_price: 1
  min_avg_daily_volume: 500000
  min_market_cap: 1000000000
  preferred_sectors:
  - Technology (infrastructure, community platforms)
  - Healthcare (community wellness)
  - Consumer Discretionary (community services)
  - Industrials (construction, infrastructure)
  - Real Estate (community development)
  - Communications (community engagement platforms)
  allowed_instruments:
  - Individual Stocks (60-80% allocation)
  - ETFs (20-40% allocation)
  - REITs (up to 10% for community development exposure)
exclusions:
  sectors: []
  tickers: []
  esg_screens: []
  local_sensitivities:
  - Companies with negative Philadelphia community impact
  - Firms opposing urban development initiatives
  - Organizations with poor labor relations in Philadelphia region
position_limits:
  max_position_pct: 10
  max_sector_pct: 30
  max_industry_pct: 20
  min_position_pct: 2
  cash_reserve_min_pct: 5
  cash_reserve_max_pct: 15
  max_international_pct: 20
  max_emerging_markets_pct: 5
  max_reit_pct: 10
  max_small_cap_pct: 15
  min_large_cap_pct: 50
portfolio_constraints:
  target_num_holdings: 18
  min_holdings: 12
  max_holdings: 25
  beta_min: 0.7
  beta_max: 1.3
  target_beta: 1.1
  target_annual_return: 12.0
  minimum_acceptable_return: 10.0
  max_portfolio_volatility: 18.0
  max_correlation_to_spy: 0.85
  min_avg_market_cap: 5000000000
  preferred_dividend_yield: 2.0
  max_portfolio_pe_ratio: 25.0
rebalancing:
  frequency: monthly
  min_trade_size_pct: 2
  max_deviation_trigger: 5
  drawdown_strategy: Sell lowest-conviction positions first
  rebalancing_priority: Maintain target allocation despite drawdowns
  market_stress_protocol: Reduce rebalancing frequency during high volatility
  opportunistic_rebalancing: Increase allocation to undervalued sectors
costs:
  commission_bps: 0
  slippage_bps: 3
  management_fee_bps: 100
  expense_ratio_target: 0.15
  max_turnover_annual: 50%
  tax_efficiency_priority: Hold positions >1 year when possible
asset_allocation:
  target_allocation:
    large_cap_growth: 35%
    large_cap_value: 20%
    mid_cap_blend: 15%
    small_cap_growth: 10%
    international_developed: 15%
    reits: 5%
  allocation_bands:
    large_cap_growth:
    - 30%
    - 40%
    large_cap_value:
    - 15%
    - 25%
    mid_cap_blend:
    - 10%
    - 20%
    small_cap_growth:
    - 5%
    - 15%
    international_developed:
    - 10%
    - 20%
    reits:
    - 0%
    - 10%
monitoring:
  benchmark_primary: S&P 500 (SPY)
  benchmark_secondary: 60/40 Stock/Bond Portfolio
  success_metrics:
  - Portfolio value progression toward $1.5M target
  - Ability to fund $10K annual drawdowns starting 2029
  - Risk-adjusted returns vs benchmarks
  - ESG/mission alignment scores
  - Downside protection during market stress
  reporting_frequency: Monthly to Connor Barwin/MTWB Board
  annual_review: Comprehensive strategy review and adjustment
risk_management:
  max_drawdown_tolerance: 25%
  stop_loss_protocol: Consider position reduction if >20% loss
  scenario_analysis:
  - 2008 Financial Crisis conditions
  - 2020 COVID market crash and recovery
  - Rising interest rate environment
  - Philadelphia local economic stress
  liquidity_requirements:
  - Maintain ability to raise $10K+ quickly for drawdowns
  - Avoid illiquid investments >5% of portfolio
  - Emergency liquidity access within 3 business days
implementation:
  investment_timeline:
  - 'Month 1-2: Initial portfolio construction'
  - 'Months 3-12: Active monitoring and adjustment'
  - 'Years 1-3: Growth focus with minimal drawdowns'
  - 'Years 3-7: Growth with annual $10K drawdowns'
  - 'Years 7-10: Position for final transformative project'
  decision_making:
    authority: Connor Barwin with advisory team consultation
    meeting_frequency: Quarterly strategy reviews
    emergency_protocols: Immediate consultation for >10% portfolio moves
  platform_constraints:
  - Use Wharton Investment Simulator for execution
  - Focus on long-term holdings vs active trading
  - Document all investment rationale for final presentation
  - Maintain detailed performance attribution records
mission_alignment:
  scoring_criteria:
    community_impact: 30%
    esg_factors: 25%
    philadelphia_relevance: 20%
    foundation_values: 15%
    financial_performance: 10%
  minimum_alignment_score: 60
  preferred_alignment_score: 80
